version: '3.9'
services:
  postgres:
    image: postgres:13
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - mynetwork
    ports:
      - '5432:5432'
  app:
    build: .
    restart: always
    networks:
      - mynetwork
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    volumes:
      - /data:/opt/app/data
networks:
  mynetwork:
    driver: bridge